Updated manager to 0.2 - Removed the build of steamworks and greenworks since the official release of screeps server - Added classy prompts :) - Updated update for server - Added package.json file

diff --git a/screepsserver b/screepsserver
--- a/screepsserver
+++ b/screepsserver
@@ -7,259 +7,199 @@ yellow="\e[93m"
 default="\e[0m"
 
 rootDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-steamcmd="${rootDir}/steamcmd"
-greenworks="${rootDir}/greenworks"
-screeps="${rootDir}/screeps"
-server="${screeps}/server"
 
-deps=("unzip" "git" "build-essential" "tmux" "nodejs")
+screepsBin="${rootDir}/node_modules/screeps/bin"
+logs="${rootDir}/logs"
+# lastLogDir="$( basename $( ls -td -- ${server}/logs/* | head -n 1 ) )"
+mods="${rootDir}/mods"
+
+deps=("python2.7" "tmux" "nodejs")
 missingDeps=()
 
 checking_dependencies () {
   nbDeps=0
-  echo -e "${red}-- [ Checking dependencies ] --${default}"
+  echo -e " ├─┬ ${yellow}Checking dependencies${default}"
   # For each dependencies we check it with dpkg-query.
   # TODO: test on other distro.
   for pkg in "${deps[@]}"; do
-	echo -e "$pkg\t\c"
-	sleep 0.5
-    dpkg-query -W -f='${Status}' "${pkg}" 2> /dev/null | grep -q -P '^install ok installed$'
-	if [ $? -eq 1 ]; then
-	  echo -e "[ ${red}MISSING${default} ]"
-	  ((nbDeps++))
-	  missingDeps+=("${pkg}")
+    if [ "${deps[-1]}" == "${pkg}" ]; then
+      echo -e " │ └─── Checking for $pkg... \t\c"
     else
-	  echo -e "[ ${green}OK${default} ]"
-	fi
+      echo -e " │ ├─── Checking for $pkg... \t\c"
+    fi
+    sleep 0.5
+    dpkg-query -W -f='${Status}' "${pkg}" 2> /dev/null | grep -q -P '^install ok installed$'
+    if [ $? -eq 1 ]; then
+      echo -e "[ ${red}MISSING${default} ]"
+      ((nbDeps++))
+      missingDeps+=("${pkg}")
+    else
+      echo -e "[ ${green}OK${default} ]"
+    fi
   done
 }
 
 install_dependencies () {
   if [[ $EUID -ne 0 ]]; then
-    # If user launch the script without sudo
+  # If user launch the script without sudo
     if [ $nbDeps -gt 0 ]; then
-	  return 1
+      return 1
     fi
-	return 0
+    return 0
   else
     # And here with sudo in front of command
-	apt-get intall "${missingDeps[@]}"
-	return 0
-  fi
-}
-
-checking_steamcmd () {
-  echo -e "${red}-- [ Checking for steamcmd ] --${default}"
-  if [ -d "${steamcmd}" ]; then
-    echo -e "[ ${green}OK${default} ] Steam folder exist"
-  else
-    echo -e "[ ${red}ERROR${default} ] Steam folder doesn't exist"
-    echo -e "${green}--> DOWNLOADING SteamCMD... ${default}"
-	sleep 0.5
-    echo ""
-    wget http://media.steampowered.com/installer/steamcmd_linux.tar.gz
-    mkdir "${steamcmd}" && cd "${steamcmd}" && tar -xzf ../steamcmd_linux.tar.gz
-    cd .. && rm steamcmd_linux.tar.gz
-    echo -e "${green}--> SteamCMD DOWNLOADED! ${default}"
-	sleep 0.5
+    apt-get intall "${missingDeps[@]}"
+    return 0
   fi
 }
 
 checking_node () {
-  echo -e "${red}-- [ Checking for NodeJS, npm & node-gyp ] --${default}"
+  echo -e " ├── ${yellow}Checking for NodeJS, npm & node-gyp${default}"
   if [[ $EUID -eq 0 ]]; then
     # TODO: Change to a check instead of install them
-	curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash
-	sudo apt-get install -y nodejs
-	sudo npm install npm@latest -g
-	sudo npm install node-gyp@latest -g
+    curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash
+    sudo apt-get install -y nodejs
+    sudo npm install npm@latest -g
+    sudo npm install node-gyp@latest -g
   else
-    echo ""
-    echo "No check have been added for nodejs 6, npm and node-gyp."
+    echo -e " ┊\n"
+    echo "No check have been added for npm and node-gyp."
     echo "Please run as root these lines after the installation : "
-	echo "curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash"
-	echo "sudo apt-get install -y nodejs"
-	echo "sudo npm install npm@latest -g"
-	echo "sudo npm install node-gyp@latest -g"
+    #echo "curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash"
+    #echo "sudo apt-get install -y nodejs"
+    echo "sudo npm install npm@latest -g"
+    echo "sudo npm install node-gyp@latest -g"
     echo ""
-	sleep 10
+    sleep 10
   fi
 }
 
-checking_archive () {
-  echo -e "${red}-- [ Checking for steamworks archive ] --${default}"
-  if [ -a "${rootDir}"/steamworks_*.zip ]; then
-    echo -e "[ ${green}OK${default} ] Archive present"
+checking_for_package_file () {
+  echo -e " ├─┬ ${yellow}Checking the package.json file${default}"
+  if [ -e ${rootDir}/package.json ]; then
+    echo -e " │ ${green}└─── The package.json file is here.${default}"
   else
-    echo -e "[ ${red}ERROR${default} ] The archive isn't present. Aborting."
-    exit 10
-  fi
-}
-
-checking_greenworks () {
-  echo -e "${red}-- [ Checking for greenworks ] --${default}"
-  if [ -d "${greenworks}" ]; then
-    echo -e "[ ${green}OK${default} ] Greenworks folder exist"
-  else
-    echo -e "[ ${red}ERROR${default} ] Greenworks doesn't exist. Cloning..."
-    echo ""
-    git clone https://github.com/greenheartgames/greenworks.git greenworks
-    echo ""
-    echo -e "${green} -> Unziping and moving SteamWorks...${default}"
-    cd "${greenworks}"/deps/ && unzip -q "${rootDir}"/steamworks_*.zip
-    mv sdk steamworks_sdk && cd "${greenworks}"
-    echo ""
-    echo -e "[ ${yellow}WARNING${default} ] ${red}The script will now automaticaly build greenworks and it'll take some time...${default}"
-    sleep 2
-    echo ""
-    npm install
-    echo ""
-    echo -e "${green}--> BUILD FINISHED! ${default}"
-  fi
-}
-
-install_all () {
-  echo -e "${blue}-- [ Installation ] -- ${default}"
-  read -e -p "-> Installing in ${rootDir} ? [y]" ok
-  if [ -z "${ok}" ]; then
-    echo ""
-	checking_dependencies
-    sleep 1
-	echo ""
-	checking_steamcmd
-    sleep 1
-    echo ""
-    checking_node
-    sleep 1
-    echo ""
-    checking_archive
-    sleep 1
-    echo ""
-	checking_greenworks
-	sleep 1
-    echo ""
-    install_screeps
-	sleep 1
-    echo ""
-    install_greenworks
-	echo ""
-	echo ""
-	echo -e "${green} -> The server has been fully installed ! You can launch it with the \"start\" command.${default}"
-	if ! install_dependencies; then
-	  echo -e "\n[ ${yellow}WARNING${default} ] Some dependencies aren't installed. Before starting your server you will need to install them."
-      echo -e "            Command to run in root user : apt-get install ${missingDeps[@]}"
-	fi
-  else
-  	echo "Installation aborted"
-  	exit 9
+    echo -e " │ ${red}├─── The package.json file is missing!${default}"
+    echo -e " │ ${blue}└─── Generating default package.json...${default}"
+    echo -e " ┊\n"
+    wget "https://raw.githubusercontent.com/iKlem/linux-screeps-server-manager/master/package.json"
+    # npm init -f --silent # Generating or Downloading a premade one ?
   fi
 }
 
 install_screeps () {
-  echo -e "${red}-- [ RUNNING INSTALLATION/UPDATE OF SCREEPS SERVER ] --${default}"
-  echo -e "${yellow}      └> This will be automated in,a next update of this script${default}"
-  read -p "Provide your Steam username: " steamUser
-  read -p "Provide the beta code: " betaCode
-  echo ""
-  "${steamcmd}"/steamcmd.sh +force_install_dir "${screeps}" +login "${steamUser}" +app_update 464350 -beta Server -betapassword "${betaCode}" validate +exit
-  echo -e "${green}-- [ SCREEPS SERVER INSTALLED/UPDATED ] --${default}"
-  echo ""
+  echo -e " ├─┬ ${yellow}Downloading Screeps server${default}\n"
+  npm install --save screeps@latest
+  echo -e " │ ${green}└─── Screeps server downloaded${default}"
+  echo -e " │"
+  echo -e " ├── ${yellow}Starting configuration${default}"
+  echo -e " ┊\n"
+  node ${screepsBin}/screeps.js init
+  echo -e "\n ┆      ${green}Done!${default}"
 }
 
-install_greenworks () {
-  echo -e "[ ${yellow}WARNING${default} ] ${red}Please wait, building in progress...${default}"
-  echo -e "[ ${yellow}WARNING${default} ] ${red}A message will appear in green when all is finished.${default}"
-  echo ""
-  sleep 2
-  cd "${server}"
-  cp "${greenworks}"/build/Release/greenworks-linux64.node "${server}"/modules/backend/greenworks/lib/greenworks-linux64.node
-  for M in modules/*/; do
-    pushd $M
-    rm node_modules -Rf
-    npm install
-    npm build
-    popd
-  done
-  pushd modules/driver/native/
-  node-gyp configure
-  node-gyp build
-  popd
-  rm logs/* -Rf
-  cd "${rootDir}"
+install_all () {
+  sleep 0.5
+  echo -e "${yellow}│${blue} Installation ${default}"
+  echo -e "${yellow}└┬─────────────┘${default}"
+  read -e -p " ├── Installing in ${rootDir} ? [y] " ok
+  if [ -z "${ok}" ]; then
+    echo " ┊"
+    checking_dependencies
+    sleep 0.5
+    echo " ┊"
+    checking_node
+    sleep 0.5
+    echo " ┊"
+    checking_for_package_file
+    sleep 0.5
+    echo " ┊"
+    install_screeps
+    sleep 0.5
+    echo -e "${green} │"
+    echo -e " └─── The server has been fully installed ! You can launch it with the \"start\" command.${default}"
+    if ! install_dependencies; then
+      echo -e "\n[ ${yellow}WARNING${default} ] Some dependencies aren't installed. Before starting your server you will need to install them."
+      echo -e "            Command to run in root user : apt-get install ${missingDeps[@]}"
+    fi
+  else
+    echo -e "${red} │"
+    echo -e " └────── Installation aborted${default}"
+    echo ""
+    exit 9
+  fi
 }
 
 check_server_up () {
   sleep 0.5
-  tmux new-session -s temp -d
-  tmux list-sessions | grep screeps > /dev/null
-  retval=$?
-  tmux kill-session -t temp
-  if [ $retval -eq 0 ]; then
-    return 0
-  else
-    return 1
-  fi
+  retval=$(tmux list-sessions 2>&1 | awk '{print $1}' | grep -Ec "screeps")
 }
 
 update_screeps () {
-  # echo "The update script doesn't exist at the moment. Sorry :( "
-  # echo "You can update the server by launching the \"install\" command."
-  install_screeps
+  # TODO: add visual and do the stop & start here.
+  stop_server
+  echo -e "\n${yellow}│${blue} Updating server ${default}"
+  echo -e "${yellow}└─────────────────┘${default}\n"
+  npm update screeps
+  start_server
 }
 
-launch_server () {
-  echo -e "${blue}Launching Screeps Private server...${default} \c"
-  if check_server_up; then
-    echo -e "[ ${red}ERROR${default} ]"
-    echo -e " └> Server is already started. You can't start more than 1 server with this script (wait for a next update ;) )"
+start_server () {
+  echo -e "${yellow}│${blue} Starting server ${default}"
+  echo -e "${yellow}└┬────────────────┘${default}"
+  check_server_up
+  if [ $retval -eq 1 ]; then
+    echo -e "${red} └── Error: Server is already started. You can't start more than 1 server with this script (wait for a next update ;) )${default}\n  "
     exit 2
   else
-    if [ -d "${screeps}" ]; then
-      cd "${server}" && tmux new-session -s screeps -d && tmux send-keys -t screeps "node modules/launcher/bin/screeps.js start" ENTER
-      if check_server_up; then
-        echo -e "[ ${green}OK${default} ]"
-        echo -e " ├> Type 'tmux attach -t screeps' to get to the server screen"
-        echo -e " ├> Do CTRL+B and d to detach from the server screen"
-        echo -e " └> More commands/informations with the \"$0 help\" command"
+    if [ -d "${screepsBin}" ]; then
+      tmux new-session -s screeps -d && tmux send-keys -t screeps "node ${screepsBin}/screeps.js start" ENTER
+      check_server_up
+      if [ $retval -eq 1 ]; then
+        echo -e " ${green}└─┬ Server started${default}"
+        echo -e "   ├─── Type 'tmux attach -t screeps' to get to the server screen"
+        echo -e "   ├─── Do CTRL+B and d to detach from the server screen"
+        echo -e "   └─── More commands/informations with the \"$0 help\" command"
       else
         echo -e "[ ${red}ERROR${default} ]"
-        echo -e " └> There was an error when starting the server..."
+        echo -e " └── There was an error when starting the server..."
         exit 3
       fi
     else
       echo -e "[ ${red}ERROR${default} ]"
-      echo -e " └> The server isn't installed. Please launch the installer with \"$0 install\""
+      echo -e " └── The server isn't installed. Please launch the installer with \"$0 install\"\n"
       exit 4
     fi
   fi
 }
 
 stop_server () {
-  echo -e "${blue}Stopping server...${default} \c\t"
-  if check_server_up; then
+  echo -e "${yellow}│${blue} Stopping server ${default}"
+  echo -e "${yellow}└┬────────────────┘${default}"
+  check_server_up
+  if [ $retval -eq 1 ]; then
     tmux kill-session -t screeps
-    if ! check_server_up; then
-      echo -e "[ ${green}OK${default} ]"
+    sleep 0.5
+    check_server_up
+    if [ $retval -eq 0 ]; then
+      echo -e "${green} └── Server is stopped!${default}"
     else
       echo -e "[ ${green}OK?${default} ]"
     fi
   else
-    echo -e "[ ${red}ERROR${default} ]"
-    echo -e " └> Server isn't started. No need to stop it."
-    exit 6
+    echo -e "${red} └── ERROR: Server isn't started. No need to stop it.${default}\n"
   fi
 }
 
-open_cli_console () {	
-  sleep 2 && clear
-  echo -e "${blue}Opening Screeps CLI...${default} (CTRL+C two times to quit) \c"
-  if check_server_up; then
-    echo -e "[${green}OK${default}]"
-	echo ""
-    cd "${server}" && node modules/launcher/bin/screeps.js cli
+open_cli_console () {
+  echo -e "${yellow}│${blue} Opening Screeps CLI...${default}   (CTRL+C two times to quit)"
+  echo -e "${yellow}└┬───────────────────────┘${default}"
+  check_server_up
+  if [ $retval -eq 1 ]; then
+    echo ""
+    node "${screepsBin}"/screeps.js cli
   else
-    echo -e "[ ${red}ERROR${default} ]"
-    echo -e " └> The server can't be reached. Maybe it's not started?"
+    echo -e "${red} └── ERROR: The server can't be reached. Maybe it's not started?${default}\n"
     exit 5
   fi
 }
@@ -267,28 +207,29 @@ open_cli_console () {
 usage () {
   echo "Usage : $0 cmd"
   echo ""
-  echo -e "${yellow}Commands${default}"
-  echo -e "  install, i \t - Install the dependencies and the Screeps server"
-  echo -e "  start,   st\t - Launch the server"
-  echo -e "  stop,    sp\t - Stop the server"
-  echo -e "  cli        \t - Open the Screeps CLI (server need to be started)"
-  echo -e "  update,  u \t - Update the server"
-  # echo -e "  backend, b \t - Open the backend log file and print it (not implemented)"
-  echo -e "  help,    h \t - Show this command list"
+  echo -e "${yellow}│${blue} Commands ${default}"
+  echo -e "${yellow}└┬─────────┘${default}"
+  echo -e " ├── install, i \t - Install the dependencies and the Screeps server"
+  echo -e " ├── start,   st\t - Launch the server"
+  echo -e " ├── stop,    sp\t - Stop the server"
+  echo -e " ├── cli        \t - Open the Screeps CLI (server need to be started)"
+  echo -e " ├── update,  u \t - Update the server"
+  echo -e " └── help,    h \t - Show this command list"
   echo ""
 }
 
-echo " [ Screeps Server Manager for Linux ]"
-echo "   Made by iKlem      -      v0.1.3"
-echo "   https://github.com/iKlem"
+echo -e "${yellow}┌──────────────────────────────────┐${default}"
+echo -e "${blue}  Screeps Server Manager for Linux${default}"
+echo -e "${yellow}└┬─────────────────────────────────┘${default}"
+echo " ├── Made by iKlem - v0.2"
+echo " └── https://github.com/iKlem"
 echo ""
 case "$1" in
   i|install)
-    sleep 1
     install_all
     ;;
   st|start)
-    launch_server
+    start_server
     ;;
   sp|stop)
     stop_server
@@ -296,8 +237,10 @@ case "$1" in
   cli)
     open_cli_console
     ;;
+  config)
+    start_config
+    ;;
   u|update)
-    stop_server
     update_screeps
     ;;
   h|help)
