Updated functions Done some rework on code, more readable Bump to 0.1.3

diff --git a/screepsserver b/screepsserver
--- a/screepsserver
+++ b/screepsserver
@@ -12,7 +12,7 @@ greenworks="${rootDir}/greenworks"
 screeps="${rootDir}/screeps"
 server="${screeps}/server"
 
-deps=("unzip" "git" "build-essential" "tmux")
+deps=("unzip" "git" "build-essential" "tmux" "nodejs")
 missingDeps=()
 
 checking_dependencies () {
@@ -20,14 +20,14 @@ checking_dependencies () {
   echo -e "${red}-- [ Checking dependencies ] --${default}"
   # For each dependencies we check it with dpkg-query.
   # TODO: test on other distro.
-  for pkg in ${deps[@]}; do
+  for pkg in "${deps[@]}"; do
 	echo -e "$pkg\t\c"
 	sleep 0.5
-    dpkg-query -W -f='${Status}' ${pkg} 2> /dev/null | grep -q -P '^install ok installed$'
+    dpkg-query -W -f='${Status}' "${pkg}" 2> /dev/null | grep -q -P '^install ok installed$'
 	if [ $? -eq 1 ]; then
 	  echo -e "[ ${red}MISSING${default} ]"
 	  ((nbDeps++))
-	  missingDeps+=(${pkg})
+	  missingDeps+=("${pkg}")
     else
 	  echo -e "[ ${green}OK${default} ]"
 	fi
@@ -43,14 +43,14 @@ install_dependencies () {
 	return 0
   else
     # And here with sudo in front of command
-	apt-get intall ${missingDeps[@]}
+	apt-get intall "${missingDeps[@]}"
 	return 0
   fi
 }
 
 checking_steamcmd () {
   echo -e "${red}-- [ Checking for steamcmd ] --${default}"
-  if [ -d ${steamcmd} ]; then
+  if [ -d "${steamcmd}" ]; then
     echo -e "[ ${green}OK${default} ] Steam folder exist"
   else
     echo -e "[ ${red}ERROR${default} ] Steam folder doesn't exist"
@@ -58,18 +58,70 @@ checking_steamcmd () {
 	sleep 0.5
     echo ""
     wget http://media.steampowered.com/installer/steamcmd_linux.tar.gz
-    mkdir ${steamcmd} && cd ${steamcmd} && tar -xzf ../steamcmd_linux.tar.gz
+    mkdir "${steamcmd}" && cd "${steamcmd}" && tar -xzf ../steamcmd_linux.tar.gz
     cd .. && rm steamcmd_linux.tar.gz
     echo -e "${green}--> SteamCMD DOWNLOADED! ${default}"
 	sleep 0.5
-fi
+  fi
+}
+
+checking_node () {
+  echo -e "${red}-- [ Checking for NodeJS, npm & node-gyp ] --${default}"
+  if [[ $EUID -eq 0 ]]; then
+    # TODO: Change to a check instead of install them
+	curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash
+	sudo apt-get install -y nodejs
+	sudo npm install npm@latest -g
+	sudo npm install node-gyp@latest -g
+  else
+    echo ""
+    echo "No check have been added for nodejs 6, npm and node-gyp."
+    echo "Please run as root these lines after the installation : "
+	echo "curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash"
+	echo "sudo apt-get install -y nodejs"
+	echo "sudo npm install npm@latest -g"
+	echo "sudo npm install node-gyp@latest -g"
+    echo ""
+	sleep 10
+  fi
+}
+
+checking_archive () {
+  echo -e "${red}-- [ Checking for steamworks archive ] --${default}"
+  if [ -a "${rootDir}"/steamworks_*.zip ]; then
+    echo -e "[ ${green}OK${default} ] Archive present"
+  else
+    echo -e "[ ${red}ERROR${default} ] The archive isn't present. Aborting."
+    exit 10
+  fi
+}
+
+checking_greenworks () {
+  echo -e "${red}-- [ Checking for greenworks ] --${default}"
+  if [ -d "${greenworks}" ]; then
+    echo -e "[ ${green}OK${default} ] Greenworks folder exist"
+  else
+    echo -e "[ ${red}ERROR${default} ] Greenworks doesn't exist. Cloning..."
+    echo ""
+    git clone https://github.com/greenheartgames/greenworks.git greenworks
+    echo ""
+    echo -e "${green} -> Unziping and moving SteamWorks...${default}"
+    cd "${greenworks}"/deps/ && unzip -q "${rootDir}"/steamworks_*.zip
+    mv sdk steamworks_sdk && cd "${greenworks}"
+    echo ""
+    echo -e "[ ${yellow}WARNING${default} ] ${red}The script will now automaticaly build greenworks and it'll take some time...${default}"
+    sleep 2
+    echo ""
+    npm install
+    echo ""
+    echo -e "${green}--> BUILD FINISHED! ${default}"
+  fi
 }
 
 install_all () {
   echo -e "${blue}-- [ Installation ] -- ${default}"
   read -e -p "-> Installing in ${rootDir} ? [y]" ok
-  if [ -z ${ok} ]
-  then
+  if [ -z "${ok}" ]; then
     echo ""
 	checking_dependencies
     sleep 1
@@ -77,45 +129,18 @@ install_all () {
 	checking_steamcmd
     sleep 1
     echo ""
-    echo -e "${red}-- [ Checking for NodeJS, npm & node-gyp ] --${default}"
-	# TODO: Change to a check instead of install them
-    curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash
-    sudo apt-get install -y nodejs
-    sudo npm install npm@latest -g
-    sudo npm install node-gyp@latest -g
+    checking_node
     sleep 1
     echo ""
-    echo -e "${red}-- [ Checking for steamworks archive ] --${default}"
-    if [ -a ${rootDir}/steamworks_*.zip ]
-    then
-      echo -e "[ ${green}OK${default} ] Archive present"
-    else
-      echo -e "[ ${red}ERROR${default} ] The archive isn't present. Aborting."
-      exit 10
-    fi
+    checking_archive
     sleep 1
     echo ""
-    echo -e "${red}-- [ Checking for greenworks ] --${default}"
-    if [ -d ${greenworks} ]
-    then
-      echo -e "[ ${green}OK${default} ] Greenworks folder exist"
-    else
-      echo -e "[ ${red}ERROR${default} ] Greenworks doesn't exist. Cloning..."
-      echo ""
-      git clone https://github.com/greenheartgames/greenworks.git greenworks
-      echo ""
-	  echo -e "${green} -> Unziping and moving SteamWorks...${default}"
-      cd ${greenworks}/deps/ && unzip -q ${rootDir}/steamworks_*.zip
-      mv sdk steamworks_sdk && cd ${greenworks}
-      echo ""
-      echo -e "[ ${yellow}WARNING${default} ] ${red}The script will now automaticaly build greenworks and it'll take some time...${default}"
-	  sleep 2
-      echo ""
-      npm install
-      echo ""
-      echo -e "${green}--> BUILD FINISHED! ${default}"
-    fi
+	checking_greenworks
+	sleep 1
+    echo ""
     install_screeps
+	sleep 1
+    echo ""
     install_greenworks
 	echo ""
 	echo ""
@@ -131,14 +156,12 @@ install_all () {
 }
 
 install_screeps () {
-  sleep 1
-  echo ""
   echo -e "${red}-- [ RUNNING INSTALLATION/UPDATE OF SCREEPS SERVER ] --${default}"
-  echo -e "${yellow}      └> This will be automated for the next update of this script${default}"
+  echo -e "${yellow}      └> This will be automated in,a next update of this script${default}"
   read -p "Provide your Steam username: " steamUser
   read -p "Provide the beta code: " betaCode
   echo ""
-  ${steamcmd}/steamcmd.sh +force_install_dir ${screeps} +login ${steamUser} +app_update 464350 -beta Server -betapassword ${betaCode} validate +exit
+  "${steamcmd}"/steamcmd.sh +force_install_dir "${screeps}" +login "${steamUser}" +app_update 464350 -beta Server -betapassword "${betaCode}" validate +exit
   echo -e "${green}-- [ SCREEPS SERVER INSTALLED/UPDATED ] --${default}"
   echo ""
 }
@@ -148,10 +171,9 @@ install_greenworks () {
   echo -e "[ ${yellow}WARNING${default} ] ${red}A message will appear in green when all is finished.${default}"
   echo ""
   sleep 2
-  cd ${server}
-  cp ${greenworks}/build/Release/greenworks-linux64.node ${server}/modules/backend/greenworks/lib/greenworks-linux64.node
-  for M in modules/*/;
-  do
+  cd "${server}"
+  cp "${greenworks}"/build/Release/greenworks-linux64.node "${server}"/modules/backend/greenworks/lib/greenworks-linux64.node
+  for M in modules/*/; do
     pushd $M
     rm node_modules -Rf
     npm install
@@ -163,7 +185,7 @@ install_greenworks () {
   node-gyp build
   popd
   rm logs/* -Rf
-  cd ${rootDir}
+  cd "${rootDir}"
 }
 
 check_server_up () {
@@ -172,8 +194,7 @@ check_server_up () {
   tmux list-sessions | grep screeps > /dev/null
   retval=$?
   tmux kill-session -t temp
-  if [ $retval -eq 0 ]
-  then
+  if [ $retval -eq 0 ]; then
     return 0
   else
     return 1
@@ -188,16 +209,14 @@ update_screeps () {
 
 launch_server () {
   echo -e "${blue}Launching Screeps Private server...${default} \c"
-  if check_server_up;
-  then
+  if check_server_up; then
     echo -e "[ ${red}ERROR${default} ]"
     echo -e " └> Server is already started. You can't start more than 1 server with this script (wait for a next update ;) )"
     exit 2
   else
-    if [ -d ${screeps} ]; then
-      cd ${server} && tmux new-session -s screeps -d && tmux send-keys -t screeps "node modules/launcher/bin/screeps.js start" ENTER
-      if check_server_up;
-      then
+    if [ -d "${screeps}" ]; then
+      cd "${server}" && tmux new-session -s screeps -d && tmux send-keys -t screeps "node modules/launcher/bin/screeps.js start" ENTER
+      if check_server_up; then
         echo -e "[ ${green}OK${default} ]"
         echo -e " ├> Type 'tmux attach -t screeps' to get to the server screen"
         echo -e " ├> Do CTRL+B and d to detach from the server screen"
@@ -217,11 +236,9 @@ launch_server () {
 
 stop_server () {
   echo -e "${blue}Stopping server...${default} \c\t"
-  if check_server_up;
-  then
+  if check_server_up; then
     tmux kill-session -t screeps
-    if ! check_server_up;
-    then
+    if ! check_server_up; then
       echo -e "[ ${green}OK${default} ]"
     else
       echo -e "[ ${green}OK?${default} ]"
@@ -236,11 +253,10 @@ stop_server () {
 open_cli_console () {	
   sleep 2 && clear
   echo -e "${blue}Opening Screeps CLI...${default} (CTRL+C two times to quit) \c"
-  if check_server_up;
-  then
+  if check_server_up; then
     echo -e "[${green}OK${default}]"
 	echo ""
-    cd ${server} && node modules/launcher/bin/screeps.js cli
+    cd "${server}" && node modules/launcher/bin/screeps.js cli
   else
     echo -e "[ ${red}ERROR${default} ]"
     echo -e " └> The server can't be reached. Maybe it's not started?"
@@ -263,7 +279,7 @@ usage () {
 }
 
 echo " [ Screeps Server Manager for Linux ]"
-echo "   Made by iKlem      -        v0.1"
+echo "   Made by iKlem      -      v0.1.3"
 echo "   https://github.com/iKlem"
 echo ""
 case "$1" in
